CREATE TABLE pick_stats (
  pick_stat_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  team_member_id  INTEGER REFERENCES team_members(team_member_id) ON DELETE CASCADE NOT NULL,
  pick_date date NOT NULL DEFAULT now(),
  pick_total NUMERIC NOT NULL DEFAULT 0,
  pick_percent NUMERIC NOT NULL DEFAULT 0,
  pick_inf NUMERIC NOT NULL DEFAULT 0
);